


const foods =[
  {id:1 , 
   name:'Wallenberg',
   helNamn:'Wallenbergare med potatismos',
   ingred:'Wallenberg (130g), Potatismos (120g), Brunsås (80g), Lingonsylt (20g)',
   spec:'Kcal 651, Protein 27g, Kolhydrater 38g, Fett 43g, Lingonsylt:, Kcal 30 , Kolhydrater 7.5g',
   img:'/images/wallenberg.png',
   pris: 89,
   gluten:true,
   laktos:true,
   vegan:false,
   kall:false
  },

  {id:2 ,
   name:'Köttbullar',
   helNamn:'Köttbullar(Nöt)',
   ingred:'Köttbullar 8st (112g), Potatismos (120g), Brunsås (80g)',
   spec:'Kcal 500, Protein 15g, Kolhydrater 38g, Fett 32g',
    mat:'Nöt', 
    img:'/images/köttbulle.png',
    gluten:true,
    laktos:true,
    vegan:false,
    kall:false
  },

  {id:3 ,
   name:'Kyckling Curry-pasta',
   helNamn:'Kyckling Curry-pasta',
   mat:'Kyckling', 
   img:'/images/pasta.png',
   ingred:'Pennepasta (200g), Kycklingröra med curry (100g)',
   spec:'Kcal 553, Protein 30g, Kolhydrater 79g, Fett 13',
   gluten:false,
   laktos:true,
   vegan:false,
   kall:true
  
  },
  {id:4 ,
  name:'Spicy Tuna pasta',
  helNamn:'Kall pasta med tonfiskröra',
  img:'/images/tuna.png',
  ingred:'Pennepasta (200g), Tonfiskröra med jalapeños (80g)',
  spec:'Kcal 554, Protein 26g, Kolhydrater 63g, Fett 22',
  gluten:false,
  laktos:true,
  vegan:false,
  kall:true
    },

  {id:5 ,
   name:'Kyckling Tikka Masala',
   helNamn:'Indisk kycklinggryta med ris', 
   img:'/images/tikka.png',
   ingred:'Kycklinggryta (200g), Basmatiris (150g)',
   spec:'Kcal 615, Protein 55.5g, Kolhydrater 69g, Fett 13',
   gluten:true,
   laktos:true,
   vegan:false,
   kall:false
  },

  {id:6 ,
   name:'Teriyaki', 
   helNamn:'Nötfärs (teriyaki) med ris',
   img:'/images/teriyaki.png',
   ingred:'Teriyaki beef (150g), Basmatiris (150g)',
   spec:'Kcal 629, Protein 46g, Kolhydrater 64g, Fett 21',
   gluten:true,
   laktos:true,
   vegan:false,
   kall:false
  },

  {id: 7 ,
  name:'Bygglådan',
  helNamn:'Kycklingfilé med ris (Bygglådan)', 
  img:'/images/bygg.png',
  ingred:'Grillad kycklingfilé (220g), Basmatiris (100g), Gröna bönor (5g)',
  spec:'Kcal 605, Protein 68g, Kolhydrater 63g, Fett 9',
  gluten:true,
  laktos:true,
  vegan:false,
  kall:false
  },

  {id: 8 ,
  name:'Stroganoff',
  helNamn:'Korvstroganoff med ris (Fläskfri, gjord på kyckling & nötkött) ', 
  img:'/images/stoganoff.png',
  ingred:'Korvstroganoff (200g), Basmatiris (130g)',
  spec:'Kcal 468, Protein 38g, Kolhydrater 52g, Fett 12',
  gluten:true,
  laktos:true,
  vegan:false,
  kall:false
  },

  {id: 9 ,
  name:'Thaigrytan',
  helNamn:'Thai-kycklinggryta med ris',
  img:'/images/thai.png',
  ingred:'Kycklingfilé med wokgrönsaker och kokosmjölk (250g), Basmatiris (100g)',
  spec:'Kcal 605, Protein 68g, Kolhydrater 63g, Fett 9',
  gluten:true,
  laktos:true,
  vegan:false,
  kall:false
  },

  {id: 10 ,
  name:'Taco', 
  helNamn:'Nötfärs (taco) med ris', 
  img:'/images/taco.png',
  ingred:'Nötfärs 10% (120g), Basmatiris (100g), Morötter (50g), Paprika (50g)',
  spec:'Kcal 478, Protein 32g, Kolhydrater 56g, Fett 14',
  gluten:true,
  laktos:true,
  vegan:false,
  kall:false
},

  {id: 11 ,
   name:'Taco+',
   helNamn:'Nötfärs (taco) med ris',
   img:'/images/taco+.png',
   ingred:'Nötfärs 10% (200g), Basmatiris (200g)',
   spec:'Kcal 713.5, Protein 56.5g, Kolhydrater 64.5g, Fett 25.5',
   gluten:true,
   laktos:true,
   vegan:false,
   kall:false
  },

  {id: 12 ,
  name:'Fitness',
  helNamn:'Kycklingfilé med ris & morötter (Fitness)',
  img:'/images/fitness.png',
  ingred:'Grillad kycklingfilé (110g), Basmatiris (130g), Morötter (80g)',
  spec:'Kcal 457, Protein 37g, Kolhydrater 66g, Fett 5',
  gluten:true,
  laktos:true,
  vegan:false,
  kall:false
  },

  {id: 13 ,
  name:'Lax med Potatis',
  helNamn:'Laxfilé med potatis & sås',
  img:'/images/lax.png',
  ingred:'Laxfilé (120g), Ugnsrostad potatis (150g), Vitlökssås',
  spec:'Kcal 495, Protein 25g, Kolhydrater 29g, Fett 31',
  gluten:true,
  laktos:true,
  vegan:false,
  kall:false
  },

  {id: 14 ,
  name:'Högrevsgryta',
  helNamn:'Högrevsgryta med ris',
  img:'/images/högrev.png',
  ingred:'Högrevsgryta (180g), Basmatiris (120g)',
  spec:'Kcal 545, Protein 38g, Kolhydrater 60g, Fett 17',
  gluten:true,
  laktos:true,
  vegan:false,
  kall:false
  },

  {id: 15 ,
   name:'Bolognese by Daki',
   helNamn:'Spaghetti bolognese',
   img:'/images/bolognese.png',
   ingred:'Glutenfri spaghetti (180g), Nötfärs bolognese 10% (150g)',
   spec:'Kcal 506, Protein 30g, Kolhydrater 51.5g, Fett 20',
   gluten:true,
   laktos:true,
   vegan:false,
   kall:false
  },

  {id: 16,
  name:'Proteinlasagne', 
  helNamn:'Lasagne med nötfärs', 
  img:'/images/proteinlas.png',
  ingred:'Lasagneplattor ,Nötfärs 10%, Bechamelsås, Ost',
  spec:'Kcal 514, Protein 38.5g, Kolhydrater 28g, Fett 27.5',
  gluten:false,
  laktos:false,
  vegan:false,
  kall:false,
  protein: true
  },

  {id: 17 ,
   name:'Vegobullar', 
   helNamn:'Vegobullar med potatismos', 
   img:'/images/vego.png',
   ingred:'Vegobullar (150g), Potatismos (150g), Brunsås (80g)',
   spec:'Kcal 479, Protein 27g, Kolhydrater 40g, Fett 23.5',
   gluten:true,
   laktos:true,
   vegan:true,
   kall:false
  },

  {id: 18 ,
   name:'Falafel', 
   helNamn:'Falafel med bulgur', 
   img:'/images/falafel.png',
   ingred:'Falafel (90g, Bulgur (170g), Kikärtssallad (50g), Hummus (50g), Ajvar (50g)',
   spec:'Kcal 610, Protein 23g, Kolhydrater 80g, Fett 22',
   gluten:false,
   laktos:true,
   vegan:true,
   kall:true
  },

  {id: 19 ,
  name:'Sås', 
  helNamn:'Sås för extra smak!', 
  img:'/images/sås.png',
  ingred:'Vitlökssås,  Curry ',
  spec:' Vitlök: Kcal 56 , Protein 0g ,Kolhydrater 0.5g ,Fett 6g, Curry: Kcal 94 , Protein 0g , Kolhydrater 1g , Fett 10g',
  gluten:true,
  laktos:true,
  vegan:false,
  kall:false
},
{id: 20 ,
  name:'Dricka', 
  helNamn:'Kall dricka till maten!', 
  img:'/images/drinks.png',
  ingred:'Vitlökssås,  Curry ',
  spec:' Vitlök: Kcal 56 , Protein 0g ,Kolhydrater 0.5g ,Fett 6g, Curry: Kcal 94 , Protein 0g , Kolhydrater 1g , Fett 10g',
  gluten:true,
  laktos:true,
  vegan:false,
  kall:false
},
]


export default foods;